import { Inter } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import Navbar from "@/components/navbar/Navbar";
import logo from "../assets/Logo.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Weather Company",
    description: "Generated by create next app",
    icons: {
        icon: "./favicon.ico",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <meta charSet="UTF-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@400;500;600;700&display=swap"
                    rel="stylesheet"
                />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body className={inter.className}>
                <Box>
                    <Navbar />
                </Box>

                {children}
            </body>
        </html>
    );
}
