import HomePage from "@/pages/home/Home";

export const metadata = {
    title: "Weather Company",
    description: "Generated by create next app",
    icons: {
        icon: "./favicon.ico",
    },
};
export default function Home() {
    return (
        <>
            <HomePage />
        </>
    );
}
