import Asia from "@/pages/asia/Asia";
import React from "react";
export const metadata = {
    title: "Weather Company | Asia",
    description: "Generated by create next app",
    icons: {
        icon: "./favicon.ico",
    },
};

function page() {
    return (
        <div>
            <Asia />
        </div>
    );
}

export default page;
